### ISSUE TITLE
241122_html, css 실습

### ISSUE THREAD

**Issue by s01d0ut** [s01d0ut/20241122#1]
### 이미지 경로 문제
1. 로컬 및 GitHub Page 에서 이미지 로드가 안되는 문제 발생
     -> 상대 경로(../)를 사용해서 HTML과 CSS, 이미지 간의 파일 위치를 정확히 맞추는 방법을 이해함
          `<img src="../image/교동.jpg" alt="교동">`
2. 상대 경로로 이미지 경로를 지정했을 때 라이브 서버에서는 잘 보이지만 GitHub Page에서는 노출되지 않는 오류 발생
     -> 절대 경로로 `<img  src="/20241122/today/image/교동.jpg" alt="교동" title="쿨쿨 잠자는 교동이">` 지정하여 문제 해결
GitHub Pages와 VS Code 라이브 서버의 차이를 알게 되었고 경로 설정이 다르게 적용될 수 있다는 점을 배움

### VS Code 라이브 서버와 실제 GitHub pages 환경의 차이
1. VS Code의 라이브 서버는 로컬 컴퓨터에서 빠르게 결과를 확인할 수 있는 편리한 도구이지만 GitHub Pages와 같은 실제 웹 배포 환경과는 동작 방식에 차이가 있을 수 있다는 점을 배움
2. 특히 절대 경로 설정 시 로컬에서는 잘 작동하더라도 GitHub Pages에서는 저장소 이름이 포함되어야 한다는 점을 이해함

----
### **진행사항**
1. 기본 프로필 작업 완료 
https://s01d0ut.github.io/20241122/today/html/Profile.html
2. 심화 프로필 작업 중

**Comment by RunaUXLabs** [comment]
어맛, 한교동씨 좋아하는구나?ㅎㅎ

1교시때 왜 루트 설정하는 방법을 그렇게 알려주었을까? 와
저 경로 안되는것을 뜯어 보면서 내 리포지토리 상위폴더를 일부러 vscode 로컬 환경루트로 잡은 이유와 매칭해보면 좋을 것 같아요!
