### ISSUE TITLE
241125_html, css 실습

### ISSUE THREAD

**Issue by s01d0ut** [s01d0ut/20241122#2]
### **1. GitHub 이미지/CSS 로딩 문제**_해결완료
- GitHub에 업로드 시 이미지와 CSS가 제대로 표시되지 않는 문제 발생
- 경로 설정에 문제가 있는 것으로 추정됨.. 저번 시간에 적용한 방법으로도 해결되지 않아 다른 해결책을 찾는 중..........
![image](https://github.com/user-attachments/assets/7a7d68e3-2228-40a3-89b5-9ff3a9f39b4e)
`/20241122/today/css/profile2.css` : _그저께는 됐는데 오늘은 안될 수도 있는 건가...? 코딩이란 참 어렵다... 뒷쳐질까봐 걱정된다.._

=> 원인: 한글이었던 파일명을 영어로 바꾸니까 해결됨.. 어제는 '교동.jpg'로 했을 때 이상이 없어서 몰랐는데, 한 파일에 한글 파일명이 여러개 들어가면서 오류가 생긴 거 같음.. 앞으로는 무조건 영어이름을 사용하자!
 
 
 
 
### **2. 배경 디자인 구현 어려움**_차차 알아가자
- 원하는 디자인
페이지 전체에 박스 이미지 배치하고 main 영역에 토마토 이미지 배치, mian 영역 토마토 이미지 위에 프로필 정보가 들어갈 블러 효과가 적용된 컨테이너 박스 배치
-> 이미지 위에 이미지 위에 블러박스 구조를 만들고 싶었는데 다른 문제들을 해결하다보니 건들지 못함..ㅜㅜ 
일단은 main 크기만큼의 토마토 이미지는 빼고 배경 이미지 위에 블러박스를 두는 것으로 변경

### **진행사항**
기본 프로필 작업 완료
https://s01d0ut.github.io/20241122/today/html/Profile.html
심화 프로필 작업은 완료
https://s01d0ut.github.io/20241122/today/html/Profile2.html

**오늘 알바 퇴근 후 해결 안되면 모종판에 꼭 모 심기...

**Comment by KwanLee1129** [comment]
멋쟁이 도마도가 되겠네요
