### ISSUE TITLE
241126_js 맛보기

### ISSUE THREAD

**Issue by s01d0ut** [s01d0ut/20241122#3]
### **하면서 궁금했던 점**
1. 현재 아이템들이 모여있는 박스에서 버튼을 클릭하면 카트에 담기는데 내용이 늘어남에 따라 전체가 위아래로 동시에 늘어남
값이 추가될 때 위아래로 늘어나는 것이 아니라 아래로만 늘어나게 하고 싶음 (위는 고정)
![image](https://github.com/user-attachments/assets/0ee3632a-8260-42b1-b0f4-aff9163eb347)

**### 진행사항**
키오스크 완성_아웃풋은 초딩같지만 재밌다
https://s01d0ut.github.io/20241122/today/html/kiosk.html

**Comment by KwanLee1129** [comment]
먼가 동물농장 크리스마스에 들어간 느낌이에요 귀엽

**Comment by syeeun09** [comment]
오 크리스마스~ 깜찍 뽀짝해여

**Comment by Min-J00ni** [comment]
연말느낌 물씬나고 좋은데용 히히 뽀둥하다,,

**Comment by RunaUXLabs** [comment]
음? 아래로 추가가 되면서 전체를 감싸고 있는 높이가 커지는건데, 위아래로 커지는 것 처럼 느껴지는거예요.
개발자 도구로 보면, 아이템이 담겨있는 상자는 변동이 없고 아래 카트에만 내용이 채워지면서 전체 높이가 늘어나고 있어요!
만약 아이템 박스는 늘상 보이고 카트만 손을 보겠다면, 카트 영역만 스크롤바를 추가하는 방법이 있지요😉
